Support LDAP authentication
stackabletech/trino-operator pull request #306
Opened 2022-10-05 15:03 UTC by maltesander

# Description

- added LDAP authentication for Trino
- upgraded operator-rs

fixes https://github.com/stackabletech/trino-operator/issues/38

## Review Checklist

- [ ] Code contains useful comments
- [ ] CRD change approved (or not applicable)
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2022-10-11 10:08 UTC, siegfriedweber requested changes

2022-10-11 10:08 UTC, siegfriedweber commented on rust/crd/src/authentication.rs
> +                    AuthenticationClass::resolve(client, authentication_class_name)
The RBAC rules must be extended:

```
 - apiGroups:
     - authentication.stackable.tech
   resources:
     - authenticationclasses
   verbs:
     - get
     - list
     - watch
 ```

2022-10-11 11:27 UTC, maltesander commented on rust/operator-binary/src/controller.rs
> +    },
Yeah its static for now and it wont happen. Not sure if this ever changes but i dont like the operator to panic.

2022-10-11 11:29 UTC, maltesander commented on docs/modules/usage_guide/pages/security.adoc
> +Please have a look at the LDAP https://github.com/stackabletech/nifi-operator/tree/main/tests/templates/kuttl/ldap[integration tests] for testing, setting up OpenLDAP and creating the integrationtest
Not sure, this is a complete working example, we could point to the docs but the user has to get familiar with the concepts if adaptations are needed?

2022-10-11 15:33 UTC, siegfriedweber requested changes

2022-10-11 15:33 UTC, siegfriedweber commented on docs/modules/usage_guide/pages/security.adoc
> +The `simple-trino-users-secret` points to a manually created secret. This contains username and password pairs as shown in the following snippet:
```suggestion
The `simple-trino-users-secret` points to a manually created secret. This contains username and password pairs as shown in the previous snippet.
```

2022-10-11 15:57 UTC, maltesander commented on docs/modules/usage_guide/pages/security.adoc
> +Please have a look at the LDAP https://github.com/stackabletech/nifi-operator/tree/main/tests/templates/kuttl/ldap[integration tests] for testing, setting up OpenLDAP and creating the integrationtest
Yeah i like that idea. And yeah it should have pointed to trino ... that was copy paste :D

2022-10-12 09:11 UTC, siegfriedweber commented on docs/modules/usage_guide/pages/security.adoc
> +Please have a look at the LDAP https://github.com/stackabletech/nifi-operator/tree/main/tests/templates/kuttl/ldap[integration tests] for testing, setting up OpenLDAP and creating the integrationtest
Ticket created: stackabletech/documentation#300

2022-10-12 09:37 UTC, maltesander commented
bors merge

2022-10-12 09:48 UTC, closed without merging