Enable logging
stackabletech/trino-operator pull request #380
Opened 2023-02-10 16:16 UTC by maltesander

# Description

fixes https://github.com/stackabletech/trino-operator/issues/376

## Review Checklist

- [ ] Code contains useful comments
- [ ] CRD change approved (or not applicable)
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2023-02-13 10:59 UTC, maltesander commented
test: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/52/

2023-02-14 16:06 UTC, siegfriedweber requested changes

2023-02-15 13:14 UTC, maltesander commented on rust/operator-binary/src/controller.rs
> +use stackable_operator::product_logging::spec::{ConfigMapLogConfig, CustomContainerLogConfig};
https://github.com/stackabletech/trino-operator/pull/380/commits/6557e0165c65502e7796c13bc5ed2d62ae169e74

2023-02-15 13:16 UTC, maltesander commented on rust/operator-binary/src/product_logging.rs
> +            LogLevel::ERROR | LogLevel::FATAL | LogLevel::NONE => Self::Error,
Good point: https://github.com/stackabletech/trino-operator/pull/380/commits/361534f7f01cc16d2d64f24f8573c2b0b228cdf3

2023-02-15 13:18 UTC, maltesander commented on tests/templates/kuttl/logging/01-install-trino-vector-aggregator.yaml
> +  name: vector-aggregator-discovery
done https://github.com/stackabletech/trino-operator/pull/380/commits/d52d22a40d94fc77492e2449fece5a27028f67e9

2023-02-15 13:18 UTC, maltesander commented on rust/operator-binary/src/product_logging.rs
> +    CrdValidationFailure { source: stackable_trino_crd::Error },
removed

2023-02-15 13:19 UTC, maltesander commented on rust/operator-binary/src/controller.rs
> +    // TODO: prepare default missing!!!
leftover, removed

2023-02-15 14:30 UTC, maltesander commented on docs/modules/usage_guide/nav.adoc
> +* xref:index.adoc[]
https://github.com/stackabletech/trino-operator/pull/380/commits/b5d733a529dc07590f730b3fc5b6277b0f44bb5f

2023-02-20 07:58 UTC, siegfriedweber commented on docs/modules/usage_guide/nav.adoc
> +* xref:index.adoc[]
`docs/modules/trino/partials/nav.adoc` must contain the the navigation entries:

```adoc
* xref:trino:getting_started/index.adoc[]
** xref:trino:getting_started/installation.adoc[]
** xref:trino:getting_started/first_steps.adoc[]
* xref:trino:configuration.adoc[]
* xref:trino:concepts.adoc[]
* xref:trino:usage_guide/index.adoc[]
** xref:trino:usage_guide/cluster.adoc[]
** xref:trino:usage_guide/configuration.adoc[]
** xref:trino:usage_guide/security.adoc[]
** xref:trino:usage_guide/monitoring.adoc[]
** xref:trino:usage_guide/log-aggregation.adoc[]
** xref:trino:usage_guide/query.adoc[]
** xref:trino:usage_guide/catalogs/index.adoc[]
*** xref:trino:usage_guide/catalogs/black-hole.adoc[]
*** xref:trino:usage_guide/catalogs/google-sheets.adoc[]
*** xref:trino:usage_guide/catalogs/hive.adoc[]
*** xref:trino:usage_guide/catalogs/iceberg.adoc[]
*** xref:trino:usage_guide/catalogs/tpcds.adoc[]
*** xref:trino:usage_guide/catalogs/tpch.adoc[]
```

`docs/modules/usage_guide/nav.adoc` must be deleted.

2023-02-20 10:44 UTC, siegfriedweber requested changes
The navigation of the documentation must be fixed. Everything else looks good to me.

2023-02-20 13:09 UTC, maltesander commented
Last test hopefully: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/54/

2023-02-20 13:30 UTC, siegfriedweber approved these changes
LGTM

2023-02-22 13:05 UTC, maltesander commented
bors merge

2023-02-22 13:11 UTC, closed without merging