Updated docs
stackabletech/trino-operator pull request #411
Opened 2023-04-13 13:17 UTC by fhennig

# Description

*Please add a description here. This will become the commit message of the merge request later.*

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2023-04-14 07:22 UTC, maltesander requested changes
Minor things. LGTM otherwise!

2023-04-14 07:22 UTC, maltesander commented on docs/modules/trino/pages/concepts.adoc
>  A Trino cluster comprises two roles: the Coordinator, responsible for managing and monitoring work loads, and the Worker, which is responsible for executing specific tasks that together make up a wor
Not part of this PR, just did not like the term "store".
```suggestion
https://trino.io/docs/current/overview/use-cases.html#what-trino-is[Trino] is a tool designed to efficiently query vast amounts of data using distributed queries. It is not a database with its own storage but rather interacts with many different data stores. Trino connects to these data stores - or data sources - via https://trino.io/docs/current/connector.html[connectors].
Each connector enables access to a specific underlying data source such as a Hive warehouse, a PostgreSQL database or a Druid instance.

A Trino cluster comprises two roles: the Coordinator, responsible for managing and monitoring work loads, and the Worker, which is responsible for executing specific tasks that together make up a work load. The workers fetch data from the connectors, execute tasks and share intermediate results. The coordinator collects and consolidates these results for the end-user.
```

2023-04-14 07:22 UTC, maltesander commented on docs/modules/trino/pages/index.adoc
> +Trino is an open-source distributed SQL query engine that enables high-speed analytics of large datasets from multiple data sources using SQL queries.This operator enables you to manage your Trino in
```suggestion
Trino is an open-source distributed SQL query engine that enables high-speed analytics of large datasets from multiple data sources using SQL queries. This operator enables you to manage your Trino instances on Kubernetes efficiently.
```

2023-04-14 07:22 UTC, maltesander commented on docs/modules/trino/pages/usage_guide/s3.adoc
> +or by referring to an external`S3Connection custom resource.
Maybe link to the S3Connection concepts page?
```suggestion
or by referring to an external S3Connection custom resource.
```

2023-04-17 06:53 UTC, fhennig commented on docs/modules/trino/pages/usage_guide/security.adoc
> +--user=admin --keystore-path=<path-to-keystore.p12> --keystore-password=<password>
It's already in a `[source]` block on a separate line

2023-04-17 07:15 UTC, maltesander approved these changes
LGTM!

2023-04-17 07:15 UTC, fhennig commented
bors merge

2023-04-17 07:19 UTC, closed without merging