[Merged by Bors] - feat: Consolidate authentication
stackabletech/trino-operator pull request #434
Opened 2023-06-15 13:36 UTC by maltesander

# Description

Changed authentication to list of authentication classes.

Multiple authentication providers can be used (file, ldap). Hot reloading works.

test: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/70/

fixes: https://github.com/stackabletech/trino-operator/issues/401

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

2023-06-20 13:55 UTC, sbernauer requested changes
First batch of comments
Some todos for me:
comment on sidecar wegen schreiben in variable und nicht direkt ins file
comment zu logging warum immer angeschaltet und nicht merged config wird
resourcen für vector checken

2023-06-20 15:24 UTC, maltesander commented on rust/operator-binary/src/authentication/mod.rs
> +                    }
Good point! https://github.com/stackabletech/trino-operator/pull/434/commits/1616383f85f16bae589a0749dd1b73f3f9a7e853

2023-06-20 15:29 UTC, maltesander commented on rust/operator-binary/src/authentication/mod.rs
> +        if !self.volumes.contains(&volume) {
It derives PartialEq, basically checks the equality of all fields in that struct.

2023-06-20 15:37 UTC, maltesander commented on rust/operator-binary/src/authentication/mod.rs
> +        debug!(
No strong opinion here, but trace is better probably.

2023-06-20 15:38 UTC, maltesander commented on docs/modules/trino/pages/usage_guide/security.adoc
> +For uniqueness, the volume mount name is internally build up of the name of the `AuthenticationClass` and the name of the referenced `Secret` concatenated with a "-" character (e.g. "simple-trino-fil
If i think about it yes, not sure why i used both auth class and secret name...ill test it without and adapt the docs.

2023-06-21 07:44 UTC, maltesander commented on docs/modules/trino/examples/usage_guide/trino-secure-internal-tls.yaml
> +  name: trino-file-auth # <3>
https://github.com/stackabletech/trino-operator/pull/434/commits/108862ed046ff40375b1e3825d81d687963e0d0e

2023-06-21 07:48 UTC, sbernauer reviewed
Should be done wit Rust code

2023-06-21 07:48 UTC, sbernauer commented on rust/operator-binary/src/authentication/mod.rs
> +        if !self.volumes.contains(&volume) {
Hm, in that case I would prefer checking for the same name

2023-06-21 08:59 UTC, maltesander commented on rust/operator-binary/src/authentication/password/mod.rs
> +pub(crate) const CONFIG_FILE_NAME_SUFFIX: &str = ".properties";
removed https://github.com/stackabletech/trino-operator/pull/434/commits/ac795ff149097f111e6b52be3fbe48ef37d986c5

2023-06-21 08:59 UTC, maltesander commented on docs/modules/trino/pages/usage_guide/security.adoc
> +For uniqueness, the volume mount name is internally build up of the name of the `AuthenticationClass` and the name of the referenced `Secret` concatenated with a "-" character (e.g. "simple-trino-fil
only authclass name now https://github.com/stackabletech/trino-operator/pull/434/commits/ac795ff149097f111e6b52be3fbe48ef37d986c5

2023-06-21 09:02 UTC, maltesander commented on rust/operator-binary/src/authentication/mod.rs
> +/// Contains all relevant information about config files, volumes etc. to enable authentication.
https://github.com/stackabletech/trino-operator/pull/434/commits/211d0b536b2d6cb8958f3d1f1fdba415d73e319d

2023-06-21 09:05 UTC, maltesander commented on rust/operator-binary/src/authentication/mod.rs
> +        debug!(
https://github.com/stackabletech/trino-operator/pull/434/commits/15c81187481dd52e2db7ba0bd3402367d879a5b9

2023-06-21 09:31 UTC, maltesander commented on rust/operator-binary/src/authentication/mod.rs
> +        if !self.volumes.contains(&volume) {
done https://github.com/stackabletech/trino-operator/pull/434/commits/d4ac56868cf6efb9bb82fe6777997bb8a036d56f

2023-06-21 09:46 UTC, maltesander commented on rust/operator-binary/src/authentication/password/file.rs
> +        .resources(ResourceRequirements {
https://github.com/stackabletech/trino-operator/pull/434/commits/6ed1939c888e10c69266591a100ce7e30613b724

2023-06-21 09:46 UTC, maltesander commented on rust/operator-binary/src/authentication/password/file.rs
> +        .command(vec!["/bin/bash".to_string(), "-c".to_string()])
done works

2023-06-21 09:57 UTC, sbernauer commented on rust/operator-binary/src/authentication/mod.rs
> +        {
```suggestion
        if !self.volumes.iter().any(|v| v.name == volume.name) {
```

2023-06-21 09:57 UTC, sbernauer commented on rust/operator-binary/src/authentication/mod.rs
> +        {
```suggestion
        if !current_volume_mounts
            .iter()
            .any(|vm| vm.name == volume_mount.name)
        {
```

2023-06-21 09:57 UTC, sbernauer commented on rust/operator-binary/src/authentication/mod.rs
> +        {
```suggestion
        if !containers_for_role.iter().any(|c| c.name == container.name) {
```

2023-06-21 09:57 UTC, sbernauer commented on rust/operator-binary/src/authentication/mod.rs
> +        if !self.volumes.contains(&volume) {
thx!

2023-06-21 10:03 UTC, sbernauer requested changes

2023-06-21 10:03 UTC, sbernauer commented on rust/operator-binary/src/controller.rs
> +            ResourceRequirements::default(),
We must pass in dedicated resources constructed using `ResourceRequirementsBuilder`.

2023-06-21 10:06 UTC, sbernauer commented
We have the same problem as in #433:
As we have decided to stuff everything into a single release we need to specify vector resources.
If you would be ok with it, I would push all the needed changes for the resources (including docs) to this branch, so that we merge them together.
Does that work for you?

2023-06-21 10:26 UTC, maltesander commented
> We have the same problem as in #433: As we have decided to stuff everything into a single release we need to specify vector resources. If you would be ok with it, I would push all the needed changes for the resources (including docs) to this branch, so that we merge them together. Does that work for you?

Works for me thanks!

2023-06-21 10:41 UTC, sbernauer commented on rust/operator-binary/src/authentication/password/file.rs
> +        .args(vec![commands.join(" && ")])
nevermind, script is newline separated and the && only for piping stdout/err

2023-06-21 13:09 UTC, sbernauer commented on tests/templates/kuttl/smoke/00-limit-range.yaml
> +# FIXME: Blocked by e.g. zookeeper not having resources set
Marker

2023-06-21 13:26 UTC, razvan commented on tests/templates/kuttl/smoke/helm-bitnami-minio-values.yaml.j2
> +    - name: hive
For some reason I cannot make suggestions here, but please replace `hive` with `trino`

2023-06-21 13:26 UTC, razvan commented on tests/templates/kuttl/smoke/04-prepare-bucket.yaml.j2
> +  - command: kubectl exec -n $NAMESPACE minio-client -- mc mb minio/trino
This should already have been done by the `provisioner` of the Minio chart.

2023-06-21 13:31 UTC, razvan reviewed
Only looked at the smoke/minio chart

2023-06-21 13:31 UTC, razvan commented on tests/templates/kuttl/smoke/helm-bitnami-minio-values.yaml.j2
> +    - name: hive
```suggestion
    - name: trino
```

2023-06-21 13:31 UTC, razvan commented on tests/templates/kuttl/smoke/00-secrets.yaml.j2
> +    password=hivehive
```suggestion
    username=trino
    password=trinotrino
```

2023-06-21 13:31 UTC, razvan commented on tests/templates/kuttl/smoke/04-prepare-bucket.yaml.j2
> +  - command: kubectl exec -n $NAMESPACE minio-client -- mc mb minio/trino
The bucket is created by the chart provisioner.

```suggestion
```

2023-06-21 13:39 UTC, sbernauer commented
@razvan my goal was to re-use the hive minio values so it was intentional. A better solution might be to call the bucket `test` everywhere. WDYT?

2023-06-21 15:10 UTC, sbernauer commented
Started test: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/71/

2023-06-22 09:51 UTC, sbernauer commented
Next try: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/72/

2023-06-27 07:02 UTC, sbernauer commented
And another https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/74/

2023-06-27 08:44 UTC, sbernauer commented
https://logs.t2.stackable.tech/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-2h,to:now))&_a=(columns:!(message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:t2-k8s-events,key:t2_cluster,negate:!f,params:(query:'2ed9a198-d2f8-45a4-abe5-ec6964c0c400'),type:phrase),query:(match_phrase:(t2_cluster:'2ed9a198-d2f8-45a4-abe5-ec6964c0c400'))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:t2-k8s-events,key:namespace,negate:!f,params:(query:kuttl-test-strong-hookworm),type:phrase),query:(match_phrase:(namespace:kuttl-test-strong-hookworm)))),index:t2-k8s-events,interval:auto,query:(language:kuery,query:''),sort:!())
`create Pod trino-coordinator-default-0 in StatefulSet trino-coordinator-default failed error: Pod "trino-coordinator-default-0" is invalid: [spec.volumes[4].name: Invalid value: "trino-with-ldap-bind-kuttl-test-strong-hookworm-bind-credentials": must be no more than 63 characters, spec.containers[1].volumeMounts[1].name: Not found: "trino-with-ldap-bind-kuttl-test-strong-hookworm-bind-credentials", spec.initContainers[0].volumeMounts[0].name: Not found: "trino-with-ldap-bind-kuttl-test-strong-hookworm-bind-credentials"]`

2023-06-29 09:15 UTC, sbernauer commented
Started test https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/75/

2023-06-29 14:23 UTC, sbernauer commented
Hopefully last test run: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/76/

2023-06-29 14:33 UTC, maltesander commented on rust/crd/Cargo.toml
> +stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.42.1" }
Lets go for 0.42.2 for smaller CRDS!

2023-06-29 14:33 UTC, maltesander commented on rust/operator-binary/Cargo.toml
> +stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.42.1" }
bump operator-rs

2023-06-29 20:07 UTC, sbernauer commented
The one and only https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/77/

2023-07-03 13:22 UTC, sbernauer commented
bors r+
Tests passed :rocket:

2023-07-03 13:43 UTC, sbernauer approved these changes
Approving together with Malte, as we have both written parts of this PR

2023-07-03 13:44 UTC, sbernauer commented
bors r+

2023-07-03 13:50 UTC, closed without merging