feat: Support experimental additional JCM arguments
stackabletech/trino-operator pull request #677
Opened 2024-12-03 11:02 UTC by sbernauer

# Description

*Please add a description here. This will become the commit message of the merge request later.*

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2025-01-15 11:13 UTC, maltesander requested changes

2025-01-15 11:13 UTC, maltesander commented on rust/operator-binary/src/config/jvm.rs
> +    fn test_jvm_config_defaults() {
I feel this is a lot of code/yamls (that may change every other version bump) for not much testing.

Not sure we need the tests at all. I think the overrides are tested properly in op-rs. If you want like a sanity/safety check i would skim it down a little (e.g. work on role and smaller defaults) and not work on the (changing) trino configs?

Happy to discuss if i miss something :)

2025-01-16 10:18 UTC, sbernauer commented on Cargo.toml
> +stackable-operator = { git = "https://github.com/stackabletech//operator-rs.git", branch = "feat/jvm-arguments" }
Pls see f2df7d1

2025-01-16 10:30 UTC, sbernauer commented on rust/operator-binary/src/config/jvm.rs
> +    jvm_args.push("# Arguments from jvmArgumentOverrides".to_owned());
I personally think the comment are helpful for most of the "standard" setups. Yes you can make them a bit misleading if you go crazy with removals, but for me personally the benefit too most users is bigger than the downside for JVM "experts"

However, I let you decide, no strong opinion

2025-01-16 10:34 UTC, sbernauer commented on rust/operator-binary/src/config/jvm.rs
> +    fn test_jvm_config_defaults() {
I personally was very happy about the tests (in op-rs and here) during development.
I think the maintenance effort is pretty low, just let the test run and copy/paste the actual output into the expected one. This applies e.g. for a new Trino version.
Also this tests comments and switching between different Trino versions, which most operators don't do.

I'm totally happy to have much easier or no tests in the other operators, but would prefer to not throw away the effort I already did and helped me developing and gaining confidence.

2025-01-16 11:27 UTC, maltesander commented on rust/operator-binary/src/config/jvm.rs
> +    jvm_args.push("# Arguments from jvmArgumentOverrides".to_owned());
Keep comments as discussed!

2025-01-16 11:36 UTC, maltesander submitted a review, later dismissed
LGTM!

2025-01-24 11:45 UTC, maltesander approved these changes
LGTM!

2025-01-24 12:03 UTC, sbernauer commented
Started https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/trino-operator-it-custom/27/

2025-01-27 16:29 UTC, maltesander approved these changes
LGTM!

2025-01-28 06:36 UTC, merged